In [12]:
import pandas as pd
import numpy as np
import joblib
import matplotlib.pyplot as plt

# Model
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

iris = load_iris()

X = iris.data
y = iris.target

print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [13]:
# model
model = KNeighborsClassifier(n_neighbors = 6)

# Split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2, stratify = y)

# fit model
model.fit(X_train,y_train)

y_pred = model.predict(X_test)

# model performance
print(model.score(X_test,y_test))

# Plot
cm = confusion_matrix(y_pred,y_test)
print(cm)

# Save model
joblib.dump(model,"iris_model.pkl")

0.9333333333333333
[[10  0  0]
 [ 0  9  1]
 [ 0  1  9]]


['iris_model.pkl']